# Generated by Django 5.2.1 on 2025-05-20 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('store_view_code', models.CharField(max_length=100, null=True)),
                ('attribute_set_code', models.CharField(max_length=100, null=True)),
                ('categories', models.CharField(max_length=100, null=True)),
                ('manufacturer_no', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('visibility', models.CharField(max_length=100, null=True)),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('also_available', models.CharField(max_length=100, null=True)),
                ('configurable_variation_labels', models.CharField(max_length=255, null=True)),
                ('configurable_variations', models.CharField(max_length=500, null=True)),
                ('product_description', models.TextField()),
                ('stock', models.CharField(max_length=255, null=True)),
                ('product_websites', models.CharField(max_length=255, null=True)),
                ('msrp_display_actual_price_type', models.CharField(max_length=100, null=True)),
                ('uom', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=255, null=True)),
                ('vendor_cost', models.CharField(max_length=255, null=True)),
                ('taxes_id', models.CharField(max_length=255, null=True)),
                ('account_number', models.CharField(max_length=255, null=True)),
                ('delivery_text', models.CharField(max_length=255, null=True)),
                ('property_account_income_id', models.CharField(max_length=255, null=True)),
                ('property_account_expense_id', models.CharField(max_length=255, null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('meta_keywords', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=255, null=True)),
                ('type_erp', models.CharField(max_length=255, null=True)),
                ('base_product_image', models.CharField(max_length=255, null=True)),
                ('base_image_label', models.CharField(max_length=255, null=True)),
                ('small_image', models.CharField(max_length=255, null=True)),
                ('small_image_label', models.CharField(max_length=255, null=True)),
                ('thumbnail_image', models.CharField(max_length=255, null=True)),
                ('thumbnail_image_label', models.CharField(max_length=255, null=True)),
                ('additional_images', models.TextField()),
                ('additional_images_label', models.CharField(max_length=255, null=True)),
                ('product_url', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('price_margin', models.CharField(max_length=20)),
                ('uom', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('type_erp', models.CharField(max_length=50)),
                ('taxes_id', models.BigIntegerField()),
                ('property_account_income_id', models.BigIntegerField()),
                ('property_account_expense_id', models.BigIntegerField()),
                ('attribute_set_code', models.CharField(max_length=50)),
                ('product_website', models.CharField(max_length=200)),
                ('meta_title_suffix', models.CharField(max_length=200)),
                ('meta_description_suffix', models.CharField(max_length=200)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('sitemap_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('is_scraping', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sitemap',
            },
        ),
        migrations.CreateModel(
            name='ProductWithErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(blank=True, max_length=500, null=True)),
                ('errors', models.TextField(null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.product')),
                ('sitemap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.sitemap')),
            ],
            options={
                'db_table': 'productwitherrors',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sitemap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.sitemap'),
        ),
    ]
