# Generated by Django 5.2.1 on 2025-05-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0002_remove_sitemap_is_scraping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='is_scraping',
            field=models.BooleanField(default=False),
        ),
    ]
