# Generated by Django 5.2.1 on 2025-05-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0003_sitemap_is_scraping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemap',
            name='is_scraping',
        ),
    ]
