# Generated by Django 5.2.1 on 2025-05-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0005_user_product_user_project_user_sitemap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwitherrors',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.user'),
        ),
    ]
