# Generated by Django 5.2.1 on 2025-05-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0006_productwitherrors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productwitherrors',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sitemap',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
