# Generated by Django 5.2.1 on 2025-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0008_user_product_user_productwitherrors_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='linenplus_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='linenplus_sku',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
