# Generated by Django 5.2.1 on 2025-05-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0009_product_flag_product_linenplus_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
