# Generated by Django 5.2.1 on 2025-05-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0012_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'sku', 'linenplus_sku')},
        ),
    ]
