# Generated by Django 5.2.1 on 2025-06-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0013_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='also_available',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='configurable_variation_labels',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
