# Generated by Django 5.2.1 on 2025-06-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0014_alter_product_also_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sitemap_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
