# Generated by Django 5.2.1 on 2025-06-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0015_project_sitemap_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemap',
            name='project_id',
        ),
        migrations.AddField(
            model_name='sitemap',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.project'),
        ),
    ]
