# Generated by Django 5.2.1 on 2025-06-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0016_remove_sitemap_project_id_sitemap_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
