# Generated by Django 5.2.1 on 2025-06-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0017_product_variation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='also_available',
        ),
    ]
