# Generated by Django 5.2.1 on 2025-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0018_remove_product_also_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='configurable_variations',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
