# Generated by Django 5.2.1 on 2025-06-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0019_alter_product_configurable_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSyncing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.PositiveSmallIntegerField(choices=[(0, 'Magento'), (1, 'Shopify')], default=0)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('token_url', models.URLField(blank=True, null=True)),
                ('admin_username', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.product')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.project')),
                ('sitemap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.sitemap')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LPsyncAdmin.user')),
            ],
        ),
    ]
