# Generated by Django 5.2.1 on 2025-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0020_projectsyncing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsyncing',
            name='endpoint_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectsyncing',
            name='token_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
