# Generated by Django 5.2.1 on 2025-06-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0021_alter_projectsyncing_endpoint_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsyncing',
            name='product',
        ),
        migrations.RemoveField(
            model_name='projectsyncing',
            name='sitemap',
        ),
    ]
