# Generated by Django 5.2.1 on 2025-06-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0022_remove_projectsyncing_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='configurable_variations',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
