# Generated by Django 5.2.1 on 2025-06-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPsyncAdmin', '0023_alter_product_configurable_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='configurable_variations',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
